- name: install docker (Linux)
  become: true
  command:
    creates: /usr/bin/docker
    cmd: |
      curl get.docker.com | sh
  when: ansible_system == "Linux"
# - name: install docker compose (Linux)
# pip:
#   name:
#     - docker-compose
# when: ansible_system == "Linux"
- name: install docker (Mac)
  community.general.homebrew_cask:
    name:
      - docker
  when: ansible_system == "Darwin"
- name: allow current user to access docker (linux)
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: yes
  when: ansible_system == "Linux"
