- name: install openvpn
  community.general.homebrew:
    name:
      - openvpn

- name: install tunnelblick
  community.general.homebrew_cask:
    name:
      - tunnelblick
  when: ansible_system == 'Darwin'
