- name: dotconfig - symlink neovim config
  file:
    path: ~/.config/nvim
    src: ~/.dotfiles/.config/nvim
    state: link
- name: dotconfig - symlink coc config
  file:
    path: ~/.config/coc
    src: ~/.dotfiles/.config/coc
    state: link
    force: true # delete pre-existing
- name: dotconfig - symlink karabiner config
  file:
    path: ~/.config/karabiner
    src: ~/.dotfiles/.config/karabiner
    state: link
    force: true
  when: ansible_system == 'Darwin'
- name: dotconfig - symlink powershell config
  file:
    path: ~/.config/powershell
    src: ~/.dotfiles/.config/powershell
    state: link
    force: true
