- name: download dotfiles
  git:
    repo: git@github.com:boxmein/dotfiles.git
    dest: ~/.dotfiles/
- name: symlink stuff (mac/linux)
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    path: "~/{{ item }}"
    force: true # delete the pre-existing versions
  loop:
    - .zshrc
    - .zshenv
    - .p10k.zsh
    - antigen.zsh
    - .vimrc
    - .vim
    - .docker
    - .gitconfig
    - .tmux.conf
    - .weechat

- name: symlink secure stuff (mac/linux)
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    path: "~/{{ item }}"
    mode: u=rw,g=,o=
    force: true # delete pre-existing versions
  loop:
    - .pgpass
    - .netrc

- name: symlink stuff (mac)
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    path: "~/{{ item }}"
  loop:
    - .hammerspoon
    - .inputrc
    - Library/KeyBindings
  when: ansible_system == "Darwin"

- name: symlink stuff (linux)
  file:
    state: link
    src: "~/.dotfiles/{{ item }}"
    path: "~/{{ item }}"
    force: true # delete pre-existing versions
  loop:
    - .xbindkeysrc
    - .xinitrc
    - .Xdefaults
    - .Xresources
    - .alacritty.yml
    - .selected_editor
  when: ansible_system == "Linux"

# Kubernetes
- name: kube config dir
  file:
    path: ~/.kube
    state: directory
- name: kube config link
  file:
    path: ~/.kube/config
    src: ~/.dotfiles/.kube/config
    state: link
    force: true # delete pre-existing versions
