- name: homebrew - install homebrew (linux)
  command:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
    cmd: |
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: ansible_system == "Linux"
  tags:
    - install
    - packages

- name: homebrew - install homebrew (Mac)
  command:
    creates: /usr/local/bin/brew
    cmd: |
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: ansible_system == "Darwin"
  tags:
    - install
    - packages

  #- name: homebrew - update homebrew repos
  #community.general.homebrew:
  #  update_homebrew: true

# - name: homebrew - upgrade homebrew packages
# community.general.homebrew:
# upgrade_all: true
