- name: homebrew_packages - set up all homebrew repos
  community.general.homebrew_tap:
    name:
      - homebrew/bundle
      - homebrew/cask
      - homebrew/cask-versions
      - homebrew/core
      - homebrew/services
      - buildkite/buildkite
      - buildkite/cli
      - github/gh
      - heroku/brew
      - jesseduffield/lazydocker
      - nektos/tap
      - windmilleng/tap
    state: present
  tags:
    - install
    - packages

- name: homebrew_packages - install all packages
  community.general.homebrew:
    name:
      - adns
      - angle-grinder
      - autoconf
      - coreutils
      - libyaml
      - openssl@1.1
      - atk
      - binutils
      - calc
      - ctop
      - libidn
      - curl-openssl
      - emscripten
      - fd
      - ffmpeg
      - fzf
      - git
      - git-lfs
      - libksba
      - npth
      - pinentry
      - gnupg
      - hicolor-icon-theme
      - htop
      - oniguruma
      - libiconv
      - libotr
      - libusb-compat
      - libuv
      - libvirt
      - mysql
      - ncdu
      - openvpn
      - p7zip
      - pg_top                    # Provides postgresql top
      - pkg-config                # Dep of other packages
      - pstree
      - pth
      - pv
      - rename
      - ripgrep
      - s-lang
      - terraform
      - the_silver_searcher
      - thefuck
      - tldr
      - transmission-cli
      - watch
      - weechat
      - wget
      - zsh
      - windmilleng/tap/tilt
  tags:
    - install
    - packages

- name: homebrew_packages - install casks
  community.general.homebrew_cask:
    name:
      - 1password-cli             # provides 1password credentials over CLI
      - cscreen                   # Provides a tool to configure monitors on Mac
      - discord
      - google-chrome
      - karabiner-elements
      - powershell
      - syncthing
      - slack
      - telegram-desktop
  when: ansible_system == "Darwin"
  tags:
    - install
    - packages
