- name: install homebrew (linux)
  command:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
    cmd: |
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: ansible_system == "Linux"

- name: install homebrew (Mac)
  command:
    creates: /usr/local/Cellar/bin/brew
    cmd: |
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: ansible_system == "Darwin"

- name: update homebrew repos
  community.general.homebrew:
    update_homebrew: true

- name: upgrade homebrew packages
  community.general.homebrew:
    upgrade_all: true
