- include_tasks: ./homebrew.yml
- include_tasks: ./homebrew_packages.yml
- include_tasks: ./dotconfig.yml
- include_tasks: ./dotfiles.yml
- include_tasks: ./asdf.yml
- include_tasks: ./neovim.yml
- include_tasks: ./macos.yml
  when: ansible_system == "Darwin"
- include_tasks: ./self_updater.yml
