- name: neovim - ensure .config exists
  file:
    path: ~/.config
    state: directory
- name: neovim - install neovim
  community.general.homebrew:
    install_options:
      - HEAD
    name:
      - neovim
    state: present
    # - name: neovim - install neovim python support
    # pip:
    # name:
    #   - neovim
    # state: present
    # when: ansible_system == "Linux"
  tags:
    - install
    - packags
- name: neovim - let neovim finish installing
  command:
    cmd: |
      nvim +PlugInstall +qall!
    creates: ~/.vim/plugged/nvim-lsp/plugin/lspconfig.vim
  tags:
    - install
