- name: self_updater - computer-setup folder
  become: true
  file:
    name: /opt/computer-setup
    state: directory
    owner: root
    group: staff
    mode: u=rwx,g=r,o=r
  tags:
    - selfupdater
- name: self_updater - copy runner to /opt
  become: true
  copy:
    src: ../../../run.sh
    dest: /opt/computer-setup/run.sh
    mode: u=rwx,g=r,o=r
    owner: root
    group: staff
  tags:
    - selfupdater
# - name: self_updater - set up a system cron task to self-update daily
#   become: true
#   cron:
#     user: root
#     cron_file: computer-setup_self-updater
#     job: /opt/computer-setup/run.sh
#     special_time: daily
